config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  devise_for :users

  root to: 'pages#home'

  resources :teams, except: [:edit, :update] do
  end

  resources :columns, except: [:index, :show] do
    resources :cards, except: [:index, :show] do
    end
  end
  get ':column_id/add_team', to: 'columns#addTeam'
  get 'filtered_teams', to: 'filters#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :columns
  has_many :cards
  # has_many :teams

  has_many :assigned_teams, dependent: :destroy
  has_many :teams, through: :assigned_teams

  has_many :assigned_cards, dependent: :destroy
  has_many :cards, through: :assigned_cards

  has_many :created_teams, class_name: 'Route'
  has_many :created_cards, class_name: 'Card'

  has_many :assigned_admins, dependent: :destroy
  has_many :teams, through: :assigned_admins
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # @user = User.find(params[:id])
    @user = current_user
    @columns = Column.where(user: current_user)
    authorize @user

    @userteams = []
    @assTeams = AssignedTeam.where(user_id: @user.id)
    @assTeams.each do |aTea|
      @userteams << aTea.team
    end
  end

  def edit
  end

  def update
  end
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<div class="row" id="user-show-navbar">
  <div class="display-flex">
    <p id="team-info"> All Teams</p>
  </div>
  <div class="display-flex" id="filter-input">
    <%= form_tag filtered_teams_path, method: "get", class: "form-inline", remote: true do %>
      <%= label_tag "Team" %>
      <%= select_tag :team, options_for_select(current_user.assigned_teams.collect{|asst| [asst.team.name]}.push("All Teams"), "All Teams")%>
      <%= submit_tag "Apply", name: nil, class:"btn btn-primary btn-sm"%>
    <% end %>
  </div>
  <div id="create">
    <%= link_to(new_column_path) do %>
      <div class="display-flex btn btn-primary btn-sm">
        <i class="fas fa-plus"></i>
        <p>New Column</p>
      </div>
    <% end %>
  </div>
  <div id="create">
    <%= link_to(new_team_path) do %>
      <div class="display-flex btn btn-primary btn-sm">
        <i class="fas fa-plus"></i>
        <p>New Team</p>
       </div>
    <% end %>
  </div>
</div>

<div class="grid-container" style="min-height: calc(100vh - 102px); padding: 0px; margin: 0px">
  <div class="row column-row" id="row-for-columns">
    <%= render 'columns/columns', columns: @columns%>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>