config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  devise_for :users

  root to: 'pages#home'

  resources :teams, except: [:edit, :update] do
  end

  resources :columns, except: [:index, :show] do
    resources :cards, except: [:index, :show] do
    end
  end
  get ':column_id/add_team', to: 'columns#addTeam'
  get 'filtered_teams', to: 'filters#index'

end

app/views/shared/_cards.html.erb
<% current_column.cards.each do |card| %>
    <div class="card card-block card-primary card-inverse card-shared" style="background-image: linear-gradient(#255965, #255965);">
      <div class="row card-category not-shared"><h5><%= card.name %></h5></div>
      <div class="row card-description">
        <div class="card-d-p">
          <p><%= card.description %></p>
        </div>
        <div class="row card-owner">
          <p>Created by: <%= card.user.first_name %> <%= card.user.last_name %></p>
          <div id="delete-button-card">
            <% if policy(card).destroy? %>
              <%= link_to "", column_card_path(current_column, card), method: :delete, data: {:confirm => 'Are you sure?'}, class:"far fa-trash-alt" %>
            <% end %>
          </div>
        </div>
      </div>
     <!--  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
      <!-- <a class="card-link" href="#" ></a> -->

    </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_indexbanner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.14) 0%, rgba(0,36,61,0.56) 50%), url('<%= image_url 'getthingsdone.jpg' %>'); ">
  <div class="banner-content">
    <h1>Lohgio</h1>
    <p>Getting things done</p>
  </div>
  <div class="banner-tabs">
    <%#= render 'shared/tab'%>
    <!-- <p>Overview of Teams</p>
    <a class="btn btn-primary btn-lg">Start now</a> -->
  </div>

</div>

app/views/shared/_indexcard.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2><%= team %></h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div>

app/views/shared/_navbar.html.erb
 <!-- -------------- -->
 <div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "lohgio_icon.png", height: 30, style: "border-radius: 50%"%>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

 <% if !user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>


    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%#= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Dashboard", users_show_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Home", routes_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Create Column", new_column_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <p>Hello <%= current_user.first_name %> <%= current_user.last_name  %></p>
      <div class="navbar-wagon-item">
      <div class="dropdown">
        <!-- <img  class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" <%#= cl_image_tag current_user.picture_url %> -->
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%#= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
        </ul>
      </div>
    <% end %>
  </div>



  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_tabs.html.erb
  <div class="team-tab tab">
    <% team.each do |t| %>
    <button class="tablinks">
      <h3><%= t.name.capitalize %></h3>
      <div id="team-show-link">
        <%= link_to "", team_path(t), class:"fas fa-columns" %>
      </div>
      <% if policy(t).destroy? %>
        <div id="team-delete-link">
          <%= link_to team_path(t), method: :delete, data: {:confirm => 'Are you sure?'} do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>
    </button>
    <% end %>
  </div>

  <div class="tabs-content-container">
    <% team.each do |t| %>
      <div class="tab-content active" id="<%=t.name.downcase%>">
        <%#= render 'shared/table', current_team: t%>
        <table id="indextable">
          <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Username</th>
                <th>HandyNr</th>
            </tr>
          </thead>
          <tbody>
            <% t.assigned_teams.each do |assT| %>
              <% user = User.find(assT.user_id) %>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.username %></td>
                <td><%= user.handy_nr %></td>
                <td><%= link_to teams_path do %>
                    <i class="fas fa-columns"></i>
                <% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <span onclick="this.parentElement.style.display='none'"><i class="far fa-eye-slash"></i></span>
      </div>
    <% end %>
  </div>
</div>