config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  devise_for :users

  root to: 'pages#home'

  resources :teams, except: [:edit, :update] do
  end

  resources :columns, except: [:index, :show] do
    resources :cards, except: [:index, :show] do
    end
  end
  get ':column_id/add_team', to: 'columns#addTeam'
  get 'filtered_teams', to: 'filters#index'

end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :user

  has_many :columns
  has_many :cards, dependent: :destroy

  has_many :assigned_columns, dependent: :destroy
  has_many :teams, through: :assigned_columns
end

app/controllers/columns/filters_controller.rb
class FiltersController < ApplicationController
  def index
    p params
    team = params[:team]
    @columns = []

    Column.where(user_id: current_user.id).each do |colmn|
      colmn.teams.each do |tms|
        if tms.name == team
          @columns << colmn
        end
      end
    end
    authorize @columns

    respond_to do |format|
      format.html { render "users/show", columns: @columns}
      format.js # views/routes/filters/index.js.erb
    end
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  def new
    @column = Column.new
    @team = Team.find(params[:team])
    authorize @column
  end

  def create
    @column = Column.new(params_column)
    @column.user = current_user
    if params[:column][:team_ids]
      @team_ids = params[:column][:team_ids].drop(1)
      @team_ids.each do |team_id|
        @team = Team.find(team_id.to_i)
        @column.teams << @team
      end
    else
      @team = Team.find(params[:team_ids])
      @column.teams << @team
    end
    authorize @column
    if @column.save
      redirect_to users_show_path
    else
      render :new
    end
  end

  def update
    @column = Column.find(params[:id])
    @team_ids = params[:column][:team_ids].drop(1)
    current_user.teams.each do |team|
      if !@team_ids.include?(team.id.to_s)
        @asC = AssignedColumn.where(team_id: team.id, column_id: @column.id)
        authorize @asC
        if !@asC[0].nil?
          @asC[0].destroy
        end
      end
    end
    @team_ids.each do |team_id|
      if team_id == "false"
        AssignedColumn.where(team_id: @team.id, column_id: @column.id).destroy
      elsif @team = Team.find(team_id.to_i)
        if !@column.teams.all? {|team| team == @team}
            @column.teams << @team
        end
      else
        render :new
      end
    end
    if @column.save
      redirect_to users_show_path
    else
      render :new
    end
  end

  def destroy
    @column = Column.find(params[:id])
    @column.destroy
    authorize @column
    redirect_to users_show_path
  end

  private

  def params_column
    params.require(:column).permit(:name, :description, :shared, :teams)
  end

  def params_updatecolumn
    params.require(:column).permit(:team_ids, :id)
  end
end

app/views/columns/_cards.html.erb
<% @columns.each do |c| %>
  <% if c.shared %>
    <div class="column column-block column-primary column-inverse column-shared" style="background-image: linear-gradient(rgba(1, 1, 1, 0.06), rgba(1, 1, 1, 0.35));">
      <div class="column-description">
        <div class="column-category shared">
          <h2><%= c.name %></h2>
          <p> </p>
        </div>
        <div class="column-txt">
          <p><%= c.description %></p>
        </div>
        <div class="cards-box">
          <%= render 'cards/cards', current_column: c%>
        </div>
      </div>

      <img class="column-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
      <!-- <a class="card-link" href="#" ></a> -->
        <div id="button-column">
          <% if policy(c).destroy? %>
            <%= link_to "", column_path(c), method: :delete, data: {:confirm => 'Are you sure?'}, class:"far fa-trash-alt" %>
          <% end %>
          <%= link_to "", new_column_card_path(c), class:"fas fa-plus" %>
        </div>
    </div>
  <% else %>
    <div class="column column-block column-primary column-inverse column-not-shared" style="background-image: linear-gradient(rgba(1, 1, 1, 0.06), rgba(1, 1, 1, 0.35));">
      <div class="column-category not-shared"><h2><%= c.name %></h2></div>
      <div class="column-description">
        <p><%= c.description %></p>
        <div class="cards-box">
          <%= render 'cards/cards', current_column: c%>
        </div>
      </div>
      <img class="column-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
      <!-- <a class="card-link" href="#" ></a> -->
      <div id="delete-button-column">
        <% if policy(c).destroy? %>
          <%= link_to "", column_path(c), method: :delete, data: {:confirm => 'Are you sure?'}, class:"far fa-trash-alt" %>
        <% end %>
      </div>
      <div id="ad-card-button">
          <%= link_to "", new_column_card_path(c), class:"fas fa-plus" %>
        </div>
    </div>
  <% end %>
<% end %>

app/views/columns/_columns.html.erb
<% @columns.each do |c| %>
  <% if c.shared %>
    <div class="column column-block column-primary column-inverse column-shared" style="background-image: linear-gradient(rgba(1, 1, 1, 0.06), rgba(1, 1, 1, 0.35));">
      <div class="column-description">
        <div class="column-category shared">
          <h2><%= c.name %></h2>
          <p> </p>
        </div>
        <div class="column-txt">
          <p><%= c.description %></p>
        </div>

        <div class="column-tab">
          <% if policy(c).update? %>
            <button class="column-tablinks" width="60">
              <p><%= c.name %><i class="far fa-eye"></i></p>

            </button>
          <% end %>
        </div>

        <div class="column-tabs-content-container">
          <div class="column-tab-content active" id="<%=c.name%>">
            <% if policy(c).update? %>
              <div class="display-flex">
                <div class="display-flex" id="filter-input">
                  <%= simple_form_for(c, url: column_path(c), remote: true) do |f|%>
                    <%= label_tag "Choose team:" %>
                    <%= f.association :teams,label: false, collection: @userteams, as: :check_boxes%>
                    <%= submit_tag "Assign", name: nil, class:"btn btn-primary btn-sm"%>
                  <% end %>
                </div>
                <div id="button-column-delete">
                  <% if policy(c).destroy? %>
                    <%= link_to "", column_path(c), method: :delete, data: {:confirm => 'Sure to delete whole COLUMN?'}, class:"far fa-trash-alt" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="cards-box">
          <%= render 'shared/cards', current_column: c%>
        </div>
        <div>
          <%= link_to "", new_column_card_path(c), class:"fas fa-plus" %>
        </div>
      </div>

      <img class="column-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
      <!-- <a class="card-link" href="#" ></a> -->
    </div>
  <% else %>
   <div class="column column-block column-primary column-inverse column-not-shared" style="background-image: linear-gradient(rgba(1, 1, 1, 0.06), rgba(1, 1, 1, 0.35));">
      <div class="column-description">
        <div class="column-category not-shared">
          <h2><%= c.name %></h2>
          <p> </p>
        </div>
        <div class="column-txt">
          <p><%= c.description %></p>
        </div>

        <div class="column-tab">
          <% if policy(c).update? %>
            <button class="column-tablinks" width="60">
              <p><%= c.name %><i class="far fa-eye"></i></p>

            </button>
          <% end %>
        </div>
        <div class="column-tabs-content-container">
          <div class="column-tab-content active" id="<%=c.name%>">
            <% if policy(c).update? %>
              <div class="display-flex">
                <div class="display-flex" id="filter-input">
                  <%= simple_form_for(c, url: column_path(c), remote: true) do |f|%>
                    <%= label_tag "Choose team:" %>
                    <%# @userteams.map {|team| team.name.capitalize} %>
                    <%= f.association :teams,label: false, collection: @userteams, as: :check_boxes%>
                    <%#= label_tag "Assign Team 2" %>
                    <%#= select_tag :user_teams, options_for_select(@userteams.collect{|u| [u.name.capitalize]})%>
                    <%= submit_tag "Assign", name: nil, class:"btn btn-primary btn-sm"%>
                  <% end %>
                </div>
                <div id="button-column-delete">
                  <% if policy(c).destroy? %>
                    <%= link_to "", column_path(c), method: :delete, data: {:confirm => 'Sure to delete whole COLUMN?'}, class:"far fa-trash-alt" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="cards-box">
          <%= render 'shared/cards', current_column: c%>
        </div>
        <div>
          <%= link_to "", new_column_card_path(c), class:"fas fa-plus" %>
        </div>
      </div>
      <img class="column-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
      <!-- <a class="card-link" href="#" ></a> -->
    </div>
  <% end %>
<% end %>

app/views/columns/new.html.erb
<div class="container">
  <h1>Create new column</h1>

  <%= simple_form_for(@column) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.label "Make Public ? " %>
    <%= f.input_field :shared, as: :radio_buttons %>
    <%# current_user.teams.each do |team| %>
    <% if params[:team] %>
      <input name="team_ids" type="hidden" value=<%= @team.id %>>
    <% else %>
      <%= f.label "Add to ? " %>
      <%= f.collection_check_boxes(:team_ids, Team.all, :id, :name) do |b| %>
        <% b.label(:"data-value" => b.value) { b.check_box + " #{b.text.capitalize} -  "} %>
      <% end %>
    <% end %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>